// ── Resume Theme Definitions ──
// Colors synced with template picker thumbnails (MiniResume in templates/page.jsx)

export const THEMES = {
  classic: {
    name: "Classic Professional",
    // Page
    pageBg: "#ffffff",
    pageBorder: "",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    // Header — deep navy (matches MiniResume classic)
    headerBg: "#1e3a8a",
    headerNameColor: "#ffffff",
    headerJobColor: "#93c5fd",
    // Sidebar — warm beige
    sidebarBg: "#fdfbf7",
    sidebarTextColor: "#374151",
    sidebarHeadingColor: "#1e3a8a",
    sidebarAccent: "#1e3a8a",
    sidebarMutedText: "#6b7280",
    // Main content
    mainTextColor: "#1f2937",
    mainHeadingColor: "#1e3a8a",
    mainAccent: "#1e3a8a",
    mainMutedText: "#6b7280",
    mainSubText: "#4b5563",
    // Misc
    skillBg: "#dbeafe",
    skillText: "#1e3a8a",
    dividerColor: "#bfdbfe",
    photoBorderColor: "#fdfbf7",
    photoFallbackBg: "#cbd5e1",
    dotBg: "#1e3a8a",
  },

  modern: {
    name: "Modern",
    pageBg: "#ffffff",
    pageBorder: "12px solid #fbbf24",
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    // Header — dark slate (matches MiniResume modern sidebar color)
    headerBg: "#334155",
    headerNameColor: "#ffffff",
    headerJobColor: "#cbd5e1",
    // Sidebar
    sidebarBg: "#e2e8f0",
    sidebarTextColor: "#334155",
    sidebarHeadingColor: "#1e293b",
    sidebarAccent: "#fbbf24",
    sidebarMutedText: "#64748b",
    mainTextColor: "#1e293b",
    mainHeadingColor: "#334155",
    mainAccent: "#334155",
    mainMutedText: "#64748b",
    mainSubText: "#475569",
    skillBg: "#fef3c7",
    skillText: "#92400e",
    dividerColor: "#cbd5e1",
    photoBorderColor: "#ffffff",
    photoFallbackBg: "#94a3b8",
    dotBg: "#334155",
  },

  glass_modern: {
    name: "Glass Modern",
    pageBg: "#ffffff",
    pageBorder: "",
    fontFamily: "'Inter', sans-serif",
    // Header — indigo-to-purple gradient (matches MiniResume glass)
    headerBg: "linear-gradient(135deg, #6366f1 0%, #a855f7 100%)",
    headerNameColor: "#ffffff",
    headerJobColor: "#c7d2fe",
    // Sidebar
    sidebarBg: "#f8fafc",
    sidebarTextColor: "#4c1d95",
    sidebarHeadingColor: "#6366f1",
    sidebarAccent: "#8b5cf6",
    sidebarMutedText: "#7c3aed",
    mainTextColor: "#1e1b4b",
    mainHeadingColor: "#6366f1",
    mainAccent: "#8b5cf6",
    mainMutedText: "#6d28d9",
    mainSubText: "#5b21b6",
    skillBg: "#ede9fe",
    skillText: "#5b21b6",
    dividerColor: "#e9d5ff",
    photoBorderColor: "#ffffff",
    photoFallbackBg: "#c4b5fd",
    dotBg: "#8b5cf6",
  },

  tech_innovator: {
    name: "Tech Innovator",
    pageBg: "#09090b",
    pageBorder: "1px solid #27272a",
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    // Header — pure black (matches dark MiniResume)
    headerBg: "#000000",
    headerNameColor: "#22c55e",
    headerJobColor: "#4ade80",
    // Sidebar — very dark zinc
    sidebarBg: "#18181b",
    sidebarTextColor: "#a1a1aa",
    sidebarHeadingColor: "#22c55e",
    sidebarAccent: "#22c55e",
    sidebarMutedText: "#52525b",
    mainTextColor: "#d4d4d8",
    mainHeadingColor: "#22c55e",
    mainAccent: "#22c55e",
    mainMutedText: "#71717a",
    mainSubText: "#a1a1aa",
    skillBg: "rgba(34,197,94,0.15)",
    skillText: "#4ade80",
    dividerColor: "#27272a",
    photoBorderColor: "#18181b",
    photoFallbackBg: "#27272a",
    dotBg: "#22c55e",
  },

  startup_vibe: {
    name: "Startup Vibe",
    pageBg: "#fcfdfe",
    pageBorder: "16px solid #10b981 none none none",
    fontFamily: "'Inter', sans-serif",
    // Header — dark gray (matches MiniResume startup)
    headerBg: "#1f2937",
    headerNameColor: "#10b981",
    headerJobColor: "#d1d5db",
    // Sidebar — light green tint
    sidebarBg: "#ecfdf5",
    sidebarTextColor: "#065f46",
    sidebarHeadingColor: "#047857",
    sidebarAccent: "#10b981",
    sidebarMutedText: "#6b7280",
    mainTextColor: "#1f2937",
    mainHeadingColor: "#047857",
    mainAccent: "#10b981",
    mainMutedText: "#6b7280",
    mainSubText: "#4b5563",
    skillBg: "#d1fae5",
    skillText: "#065f46",
    dividerColor: "#a7f3d0",
    photoBorderColor: "#ecfdf5",
    photoFallbackBg: "#1f2937",
    dotBg: "#10b981",
  },

  clean_slate: {
    name: "Clean Slate",
    pageBg: "#ffffff",
    pageBorder: "",
    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
    // Header — pure black (matches minimal MiniResume)
    headerBg: "#000000",
    headerNameColor: "#ffffff",
    headerJobColor: "#a1a1aa",
    // Sidebar — white with subtle border
    sidebarBg: "#ffffff",
    sidebarTextColor: "#3f3f46",
    sidebarHeadingColor: "#18181b",
    sidebarAccent: "#18181b",
    sidebarMutedText: "#71717a",
    mainTextColor: "#27272a",
    mainHeadingColor: "#18181b",
    mainAccent: "#18181b",
    mainMutedText: "#71717a",
    mainSubText: "#52525b",
    skillBg: "#f4f4f5",
    skillText: "#3f3f46",
    dividerColor: "#e4e4e7",
    photoBorderColor: "#ffffff",
    photoFallbackBg: "#d4d4d8",
    dotBg: "#18181b",
  },

  creative_agency: {
    name: "Creative Agency",
    pageBg: "#f8fafc",
    pageBorder: "8px solid #f97316",
    fontFamily: "'Inter', sans-serif",
    // Header — vibrant orange (matches MiniResume creative)
    headerBg: "#f97316",
    headerNameColor: "#ffffff",
    headerJobColor: "#fff7ed",
    // Sidebar — dark navy
    sidebarBg: "#1e293b",
    sidebarTextColor: "#cbd5e1",
    sidebarHeadingColor: "#fb923c",
    sidebarAccent: "#f97316",
    sidebarMutedText: "#94a3b8",
    mainTextColor: "#1c1917",
    mainHeadingColor: "#ea580c",
    mainAccent: "#f97316",
    mainMutedText: "#78716c",
    mainSubText: "#57534e",
    skillBg: "#ffedd5",
    skillText: "#9a3412",
    dividerColor: "#fed7aa",
    photoBorderColor: "#1e293b",
    photoFallbackBg: "#fb923c",
    dotBg: "#f97316",
  },
};
